//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class clones_modified_users
    {
        public string modification_id { get; set; }
        public string analyzer_id { get; set; }
        public string source_id { get; set; }
        public string status { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string file_name { get; set; }
        public Nullable<int> modified_line_number { get; set; }
    }
}
