//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class clone_class
    {
        public string cloneclass_id { get; set; }
        public Nullable<int> clone_lines_count { get; set; }
        public Nullable<int> clone_fragments_count { get; set; }
        public string source_id { get; set; }
        public string analyzer_id { get; set; }
        public string clone_class_type { get; set; }
    }
}
