//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public string source_id { get; set; }
        public string source_name { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string location { get; set; }
        public string git_url { get; set; }
        public string time_intervals_id { get; set; }
    }
}
