//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_analyzer
    {
        public string analyzer_id { get; set; }
        public Nullable<System.DateTime> processed_time { get; set; }
        public Nullable<int> source_file_count { get; set; }
        public Nullable<int> clone_classes_count { get; set; }
        public Nullable<int> clones_count { get; set; }
        public string source_id { get; set; }
        public Nullable<int> line_of_code_count { get; set; }
        public string source_path { get; set; }
    }
}
