//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_file
    {
        public string file_id { get; set; }
        public string file_path { get; set; }
        public Nullable<int> line_of_code { get; set; }
        public string source_id { get; set; }
        public string analyzer_id { get; set; }
    }
}
