//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_intervals
    {
        public string time_intervals_id { get; set; }
        public string hours_value { get; set; }
        public string display_value { get; set; }
    }
}
