//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class webhook_files
    {
        public Nullable<long> file_id { get; set; }
        public Nullable<long> webhook_ref_id { get; set; }
        public string file_name { get; set; }
        public string status { get; set; }
        public string additions { get; set; }
        public string deletions { get; set; }
        public string changes { get; set; }
        public string patch { get; set; }
        public int unique_id { get; set; }
    }
}
