//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCloneAnalysis_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class webhook
    {
        public Nullable<long> webhook_ref_id { get; set; }
        public string head_commit_id { get; set; }
        public string head_commit_url { get; set; }
        public string head_commit_message { get; set; }
        public string head_commit_added { get; set; }
        public string head_commit_removed { get; set; }
        public string head_commit_modified { get; set; }
        public string repository_id { get; set; }
        public string repository_url { get; set; }
        public Nullable<System.DateTime> entry_time { get; set; }
        public string after_id { get; set; }
        public string before_id { get; set; }
        public string source_id { get; set; }
        public int unique_id { get; set; }
    }
}
