//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclone.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webHookFile
    {
        public long fileId { get; set; }
        public Nullable<long> webHookId { get; set; }
        public string fileName { get; set; }
        public string Status { get; set; }
        public string additions { get; set; }
        public string deletions { get; set; }
        public string changes { get; set; }
        public string patch { get; set; }
    
        public virtual webHook webHook { get; set; }
    }
}
