//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclone.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webHookCommit
    {
        public long icommitId { get; set; }
        public Nullable<long> webHookId { get; set; }
        public string gitCommitId { get; set; }
        public string message { get; set; }
        public string timestamp { get; set; }
        public string url { get; set; }
        public string authorName { get; set; }
        public string authorUserName { get; set; }
        public string committerName { get; set; }
        public string committerUserName { get; set; }
        public string added { get; set; }
        public string removed { get; set; }
        public string modified { get; set; }
    
        public virtual webHook webHook { get; set; }
    }
}
